### ISSUE TITLE
maltego problem

### ISSUE THREAD

**Issue by shanow7** [megadose/facebook_totem#1]
hi I've problem with maltego transform

Running transform Name To Facebook Page on 1 entities (from entity "John Doe")
Error running local transform: java.io.IOException: Cannot run program "/usr/bin/python3" (in directory "/totem-maltego"): error=2, There is no such file or directory (from entity "John Doe")
Transform Name To Facebook Page returned with an error: Error running local transform: java.io.IOException: Cannot run program "/usr/bin/python3" (in directory "/totem-maltego"): error=2, There is no such file or directory (from entity "John Doe")
Transform Name To Facebook Page done (from entity "John Doe")
Running transform Name To Facebook Page on 1 entities (from entity "John Doe")
Error running local transform: java.io.IOException: Cannot run program "/usr/bin/python3" (in directory "/totem-maltego"): error=2, Nie ma takiego pliku ani katalogu (from entity "John Doe")
Transform Name To Facebook Page returned with an error: Error running local transform: java.io.IOException: Cannot run program "/usr/bin/python3" (in directory "/totem-maltego"): error=2, Nie ma takiego pliku ani katalogu (from entity "John Doe")
Transform Name To Facebook Page done (from entity "John Doe")

**Comment by megadose** [comment]
You did not correctly follow the installation instructions in the wiki

**Comment by megadose** [comment]
https://github.com/megadose/totem-maltego/wiki/Installation

**Comment by shanow7** [comment]
I follow but nothing change

![image](https://user-images.githubusercontent.com/37192410/87828972-5bcfc900-c87e-11ea-8c94-3908f96244ce.png)

**Comment by megadose** [comment]
You have to put the full path not just
 /totem-maltego
If you're on Linux it should look like /home/youruser/totem-maltego

**Comment by shanow7** [comment]
I have't totem-maltego only facebook_totem

![image](https://user-images.githubusercontent.com/37192410/87830975-93d90b00-c882-11ea-8f6e-fc77ecaab3bc.png)

**Comment by megadose** [comment]
So download totem-maltego if you want to install the transforms in maltego

**Comment by megadose** [comment]
https://github.com/megadose/totem-maltego

**Comment by shanow7** [comment]
it's work, thx :) but why only facebook details ads has icons?

![image](https://user-images.githubusercontent.com/37192410/87832096-7e191500-c885-11ea-89cd-aba25f482ed2.png)

**Comment by megadose** [comment]
OK perfect, they all have icons if you're talking about the preview it's probably from the fact that you have the community edition.

**Comment by shanow7** [comment]
ok, now I install toutatis-maltego and I've problem with 
![image](https://user-images.githubusercontent.com/37192410/87836399-3350ca80-c890-11ea-94fb-f74368a8f517.png)
where I will found this?

**Comment by megadose** [comment]
You have to put the full path
/home/shanow/toutatis-maltego

**Comment by shanow7** [comment]
still error
![image](https://user-images.githubusercontent.com/37192410/87852017-95481900-c8fe-11ea-9d79-315eb5faf7fa.png)

**Comment by megadose** [comment]
You have just to follow the wiki
https://github.com/megadose/toutatis-maltego/wiki/Installation

**Comment by shanow7** [comment]
I did exactly the same
![image](https://user-images.githubusercontent.com/37192410/87854763-6a68bf80-c914-11ea-883f-389908f03188.png)

**Comment by megadose** [comment]
Not exactly the same thing because the command parameters is toutatis-maltego.py and not /toutatis-maltego!    If you don't read the wiki it's normal that it doesn't work !
😉 Enjoy
